version: '3.7'

services:
  main:
    container_name: main
    build: 
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=onpause 
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: